apiVersion: v1
appVersion: 1.0.0
description: Azarc Mongo Stack
type: application
version: 1.0.0
maintainers:
  - email: wael.jammal@azarc.io
    name: Wael Jammal
name: azarc-mongo-stack
sources:
  - https://github.com/azarc-io/verathread-cloud
