apiVersion: v1
kind: Service
metadata:
  name: mongodb
spec:
  ports:
    - name: mongodb
      protocol: TCP
      port: 27017
      targetPort: mongodb
  selector:
    app: mongodb
  clusterIP: None
