apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  labels:
    app: mongodb
spec:
  selector:
    matchLabels:
      app: mongodb
  serviceName: "mongodb"
  replicas: 1
  template:
    metadata:
      name: mongodb-pod
      labels:
        app: mongodb
    spec:
      terminationGracePeriodSeconds: 10
      volumes:
        - name: custom-init-scripts
          configMap:
            name: mongodb-init-scripts
            defaultMode: 420
        - name: mongodb-keyfile
          configMap:
            name: mongodb-keyfile
            defaultMode: 0o400
      containers:
        - name: mongodb
          image: mongo
          args:
            - --bind_ip
            - '0.0.0.0,::'
            - --replSet
            - rs0
#            - --auth
#            - --keyFile
#            - /data/db/keyfile
          ports:
            - containerPort: 27017
              name: mongodb
          volumeMounts:
            - name: mongo-persistent-storage
              mountPath: /data/db
            - name: custom-init-scripts
              mountPath: /docker-entrypoint-initdb.d/
#          env:
#            - name: MONGO_INITDB_ROOT_USERNAME
#              value: root
#            - name: MONGO_INITDB_ROOT_PASSWORD
#              value: verathread2008
      initContainers:
        - name: change-ownership-container
          image: busybox
          imagePullPolicy: IfNotPresent
          command: ["/bin/sh"]
          args:
            - -c
            - >-
              /bin/cp /tmp/keyfile /data/db/keyfile &&
              /bin/chown 999:999 /data/db/keyfile &&
              /bin/chmod 400 /data/db/keyfile
          volumeMounts:
            - name: mongodb-keyfile
              mountPath: /tmp/
            - name: mongo-persistent-storage
              mountPath: /data/db
      imagePullSecrets:
        - name: ghcr-login-secret
  volumeClaimTemplates:
    - metadata:
        name: mongo-persistent-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
