{{- if .Values.local }}
apiVersion: v1
kind: Service
metadata:
  name: garnet-local
  labels:
    app.kubernetes.io/instance: garnet
    app.kubernetes.io/name: garnet
spec:
  ports:
    - name: client
      protocol: TCP
      port: 6379
      targetPort: 6379
      nodePort: 31379
  selector:
    app.kubernetes.io/instance: garnet
    app.kubernetes.io/name: garnet
  type: NodePort
  sessionAffinity: None
{{- end}}
