name: Pull Request

on:
  pull_request:
    branches: [ 'main' ]
    types:
      - opened
      - synchronize

env:
  AWS_REGION: eu-west-2
  FORCE_COLOR: 1
  DRY_RUN: false
  DEPLOY: true
  RUNNER_ALLOW_RUNASROOT: "1"
  DOCKER_REGISTRY: ghcr.io/azarc-io/verathread-dev
  GOLANGCILINT_VER: "v1.59.1"

concurrency:
  group: pr-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  verify:
    name: "Verify Docs"
    runs-on: ubuntu-latest
    env:
      GOLANGCILINT_VER: "v1.59.1"
      GOPRIVATE: "github.com/azarc-io"
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
      - name: "Setup Go"
        uses: actions/setup-go@v5
        with:
          cache-dependency-path: go.sum
          go-version-file: go.mod
      - name: "Setup Python"
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          cache: 'pip'
          cache-dependency-path: docs/requirements.txt
      - name: "Fix git URL"
        run: git config --global url."https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/".insteadOf "https://github.com/"
      - name: "Lint"
        uses: golangci/golangci-lint-action@v6.0.1
        with:
          version: ${{ env.GOLANGCILINT_VER }}
          skip-cache: true
      - name: "Install MkDocs Dependencies"
        working-directory: docs
        run: |
          pip install --upgrade pip
          task docs:install:deps
      - name: "Build Docs"
        working-directory: docs
        run: task docs:build

  e2e:
    name: "Test Tasks"
    runs-on: ubuntu-latest
    needs:
      - verify
    env:
      REGISTRY_PORT: 5000
      REGISTRY_NAME: kind-registry
      GATEWAY_REGISTRY: localhost:5000/gateway
      GATEWAY_WEB_REGISTRY: localhost:5000/gateway-web
      GATEWAY_TAG: dev
      NAMESPACE: gateway-tests
    # if: github.event_name != 'pull_request'
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: "Set up Go"
        id: setup-go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - name: "Setup Helm"
        uses: azure/setup-helm@v4.2.0
        with:
          version: v3.3.4
      - name: "Setup task"
        uses: arduino/setup-task@v2
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: "Calculate Variables"
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - name: "Run Setup"
        run: task setup
      - name: "Create Cluster"
        run: task k3d:create
      - name: "Wait 1 Min"
        run: sleep 60
      - name: "Install Dependencies"
        run: k3d:install:charts
