name: Release

on:
  push:
    branches:
      - main

env:
  RUNNER_ALLOW_RUNASROOT: "1"
  GOPRIVATE: "github.com/azarc-io"

jobs:
  release:
    name: "Tag & Release Documentation"
    runs-on: ubuntu-latest-4-cores
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      contents: write
      pages: write
      id-token: write
      deployments: write
      packages: write
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
      - name: "AWS Credentials"
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: "Setup Pages"
        uses: actions/configure-pages@v5
      - name: "Setup Python"
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          cache: 'pip'
          cache-dependency-path: docs/requirements.txt
      - name: "Setup Go"
        uses: actions/setup-go@v5
        with:
          cache-dependency-path: go.sum
          go-version-file: go.mod
      - name: "Setup task"
        uses: arduino/setup-task@v2
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: "Install Dependencies"
        working-directory: docs
        run: |
          pip install --upgrade pip
          task docs:install:deps
      - name: "Write Latest Version"
        run: |
          mkdir -p bin
          echo ${{ steps.tag.outputs.tag }} >> bin/latest.txt
      - name: "Build Docs"
        working-directory: docs
        run: task docs:build
      - name: "Bump version and push tag"
        uses: anothrNick/github-tag-action@1.67.0
        id: tag
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
          WITH_V: true
          DEFAULT_BUMP: minor
          INITIAL_VERSION: 1.0.0
      - name: "Create Site Package"
        run: |
          mkdir -p bin
          zip -r bin/site.zip docs/site
      - name: "Release VDT"
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: "~> v1"
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
          GORELEASER_CURRENT_TAG: ${{ steps.tag.outputs.tag }}
      - name: "Deploy to GitHub Pages"
        id: deployment
        uses: actions/deploy-pages@v4
